fix exitcode logging in sequential case

diff --git a/ocrd-make b/ocrd-make
--- a/ocrd-make
+++ b/ocrd-make
@@ -28,7 +28,7 @@ XFERHOST=
 XFERWORKDIR=
 XFERINIT=
 
-set -e
+set -e -o pipefail
 
 makeopts=()
 targets=()
@@ -279,7 +279,7 @@ else
     for target in "${targets[@]}"; do
         make "${makeopts[@]}" -C "$target" 2>&1 | tee -a "$target.$CFGNAME.log"
         exitcodes+=( $? )
-        ((${exitcodes[*]:(-1)}==0)) && echo -n "success:" || echo -n "failure:"
+        ((${exitcodes[-1]}==0)) && echo -n "success:" || echo -n "failure:"
         echo " $target"
     done
 fi
